language: generic
sudo: required
services: 
  - docker 
before_install: 
  - docker build -t edwixx/docker-react -f Dockerfile.dev .

script: 
  - - docker run -e CI=true edwixx/docker-react npm run test -- --coverage